### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by hihell** [danielfrg/word2vec#27]
when trying the example word2vec.word2phrase a system error occurred. 
after a short source search, I found out that is actually calling word2phrase as a command, and I've tried word2phrase command in shell and there is no such command nor word2vec.

I've installed by pip in mac(10.10.5) and there is no error, 

```
pip show word2vec
Name: word2vec
Version: v0.8.1
Location: /Library/Python/2.7/site-packages
Requires: numpy
```

could you please inform me where can I find this command? maybe append some path to $PATH?

**Comment by danielfrg** [comment]
Yes, the command is missing from the `$PATH` on your case.

It looks like you are using the system python, this is really not recommended for development. I would recommend to use homebrew to install python or using the anaconda python distribution.

If you have the output from `pip install word2vec` i could help more to find the command, it is possible that because of permissions (of using the system python) the binaries are not correctly created.

**Comment by hihell** [comment]
solved by using anaconda, thank you very much!!!
