### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by angelteers** [danielfrg/word2vec#28]
hi,I want to ask a feasibility issue.you know,the componets of the vectors are features indicating some context type.i want to get these features,my language is chinese,but i  don't know how to start. Can you give me an idea? Thank you.

**Comment by danielfrg** [comment]
Thats the great question :) The good (and at the same time bad) of word2vec is that the algorithm doesn't tell you what the features indicate. You know of course that they represent  some kind of relation between the words that have a similar value on that feature but you dont know exactly what each dimension represent.

You have to play with the number of features that the algorithm can output and see by yourself but its not an easy task.

Also in each dataset the feature will represent something different! Column 1 trained on a book will represent something for that dataset than for a different book.

There have been papers trying some techniques but I have not tried any so you have to see what works for you.

That's why clustering is an easier approach once you have the word vectors since you dont care what the features are just the distances.

Hope this helps.

**Comment by angelteers** [comment]
Thank you very much.
