### ISSUE TITLE
 [Errno 2] No such file or directory: 'word2vec'

### ISSUE THREAD

**Issue by PorridgeKiller** [danielfrg/word2vec#57]
- On MacOS 10.13.6, I've tried Python-2.7 3.5 3.6 3.7, I can exec command word2vec in terminal and get a .bin file output, but it didn't work when run with python code 
- I cloned source code from git but got the same exception.

> example:
```
import word2vec as wv

if __name__ == '__main__':
wv.word2vec('../data/dict.txt.big.txt', '/Users/porridge/Downloads/Word2Vec.bin', size=300, verbose=True)
```

> Exceptions messages such as:
```
FileNotFoundError: [Errno 2] No such file or directory: 'word2vec'
FileNotFoundError: [Errno 2] No such file or directory: 'word2phrase'
FileNotFoundError: [Errno 2] No such file or directory: 'word2clusters'
```
depends on which function I called

**Comment by wangdq1989** [comment]
Have you finished it ? I have got the same  question!

**Comment by chencjiajy** [comment]
It's because the files: 'word2vec' ,.. not in the system file.
the solution is same as [issue 36](https://github.com/danielfrg/word2vec/issues/36) and [issue 53](https://github.com/danielfrg/word2vec/issues/53)

I got this error because I have two version anaconda in my system, and the actually anaconda I use is not in the $PATH of system
